### PR TITLE
Issue 110

### PR DESCRIPTION
**Pull request by helenamachado**
added cranium breadth, cranium breadth at orbital process, cranium breadth at zygomatic arch and cranium breadth at paroccipital process

### CODE REVIEW

**Comment by helenamachado** [comment]
issue #110

**Comment by megbalk** [comment]
@helenamachado are these ready to go?

**Comment by helenamachado** [comment]
> @helenamachado are these ready to go?

Yes! just not sure if 'ectorbitale' (#111) , 'zygion' (#112) and 'paroccipital process' (#113) were added to imports yet

**Comment by megbalk** [comment]
@helenamachado were you able to update the imports?

**Pull request merged**
